// The ONE config schema. Both setup faces render from this file and nothing else:
//   - gamentic-setup (CLI) parses it (strips the JS wrapper, reads the JSON)
//   - setup.html loads it with a <script> tag (works from file://, no server)
//   - .env.example is GENERATED from it (gamentic-setup --write-example)
// Change a setting here and every face follows; edit a face by hand and you have
// re-introduced drift, so don't.
//
// Shape: modes pick which questions a user sees; groups order them; settings carry
// the prompt/help/default/validation. "advanced" settings are only asked in the
// custom mode (both faces still write their defaults into .env so compose always
// has the full picture). "setByMode" settings are answered by the mode choice
// itself. "constants" are written verbatim, never asked.
window.GAMENTIC_SETUP_SCHEMA = {
  "version": 1,
  "envFile": ".env",
  "doneMessage": "You're configured. Close this and run, from the gamentic folder:  docker compose up -d --build   (or ./up.sh)",
  "modes": [
    {
      "id": "local",
      "label": "Local (full stack, GPU)",
      "help": "Everything on this machine: text model on Vulkan, ComfyUI images, Maya1 voice. Needs an AMD GPU and the model files on disk. This is the shipping default."
    },
    {
      "id": "anna",
      "label": "Anna (no GPU, no local inference)",
      "help": "Text is served by the Anna agent running in the stack (sign in once at http://localhost:19001 after starting). Images degrade to text-only play, voice is off. Only four light containers run."
    },
    {
      "id": "custom",
      "label": "Custom (every knob)",
      "help": "All questions, including cloud providers per modality and the advanced tuning knobs. For people who already know what they want."
    }
  ],
  "groups": [
    { "id": "models", "label": "Models on disk", "modes": ["local", "custom"] },
    { "id": "gpu", "label": "GPU access", "modes": ["local", "custom"] },
    { "id": "anna", "label": "Anna", "modes": ["anna", "custom"] },
    { "id": "providers", "label": "Inference providers (cloud overrides)", "modes": ["custom"] },
    { "id": "text-llm", "label": "Text model server", "modes": ["custom"] },
    { "id": "image-service", "label": "Image services", "modes": ["custom"] },
    { "id": "image-knobs", "label": "Image behavior", "modes": ["custom"] },
    { "id": "text-knobs", "label": "Story engine tuning", "modes": ["custom"] },
    { "id": "voice", "label": "Voice", "modes": ["custom"] }
  ],
  "settings": [
    { "key": "ANNA", "group": "anna", "type": "bool", "default": "false",
      "setByMode": { "local": "false", "anna": "true" },
      "prompt": "Anna mode?",
      "help": "LITERAL true/false only. true starts orchestrator + frontend + the Anna agent + its adapter and nothing GPU-shaped; false starts the full local stack. The app reads anything non-'false' as on but compose matches only the literals, so any other value starts NO inference services (./up.sh refuses such values). Switching on a running stack: docker compose down BEFORE flipping, up after; ./up.sh handles that for you." },

    { "key": "MODELS_DIR", "group": "models", "type": "path", "default": "/home/hec/models/gguf",
      "prompt": "Folder that holds your GGUF model folders",
      "help": "Host path mounted read-only into the model containers. The text and voice model paths below are relative to this folder." },
    { "key": "LLM_TEXT_MODEL", "group": "models", "type": "path-relative", "default": "gemma-4-26B-A4B-it-heretic/gemma-4-26B-A4B-it-heretic.Q4_K_M.gguf",
      "prompt": "Text model file (relative to the models folder)",
      "help": "The one setting you MUST get right for local play. Path of the GGUF file relative to MODELS_DIR (inside the container it appears at /models/...)." },
    { "key": "LLM_ALIAS", "group": "models", "type": "string", "default": "gemma-4-26b-a4b-heretic", "advanced": true,
      "prompt": "Model alias",
      "help": "The name the llama.cpp server advertises and the orchestrator requests. Cosmetic unless you point other tools at the server." },
    { "key": "COMFY_MODELS_DIR", "group": "models", "type": "path", "default": "/home/hec/models/comfyui",
      "prompt": "ComfyUI models folder",
      "help": "Host path for ComfyUI's model store, mounted read-write (ComfyUI Manager downloads checkpoints here)." },

    { "key": "RENDER_GID", "group": "gpu", "type": "int", "default": "990",
      "prompt": "render group id",
      "help": "The numeric gid of the 'render' group on this host, so containers may use the GPU. Find it with: getent group render. The CLI detects this automatically." },
    { "key": "VIDEO_GID", "group": "gpu", "type": "int", "default": "44",
      "prompt": "video group id",
      "help": "The numeric gid of the 'video' group on this host. Find it with: getent group video. The CLI detects this automatically." },

    { "key": "ANNA_API_KEY", "group": "anna", "type": "secret", "default": "",
      "prompt": "Anna API key (sk-..., optional)",
      "help": "The hackathon-issued key. The agent stores it as its Nexus credential; the in-stack adapter needs no key of its own. Leave blank if you only sign in through the agent's Web UI." },
    { "key": "ANNA_BASE_URL", "group": "anna", "type": "string", "default": "", "advanced": true,
      "prompt": "Anna gateway base URL",
      "help": "Blank = the in-stack anna-api adapter in front of the Anna agent container (the normal case). Set a real OpenAI-compatible cloud gateway URL only if the organizers hand one out; /v1 optional, normalized per modality." },
    { "key": "ANNA_TEXT_MODEL", "group": "anna", "type": "string", "default": "", "advanced": true,
      "prompt": "Anna text model name",
      "help": "Blank = anna-copilot (the adapter accepts anything). Only matters against a real cloud gateway." },
    { "key": "ANNA_IMAGE_MODEL", "group": "anna", "type": "string", "default": "", "advanced": true,
      "prompt": "Anna image model name",
      "help": "Blank = gpt-image-2. Only matters against a real cloud gateway that serves images." },
    { "key": "ANNA_AGENT_USERNAME", "group": "anna", "type": "string", "default": "", "advanced": true,
      "prompt": "Agent local username (fallback)",
      "help": "Fallback only: the adapter normally rides the Web UI sign-in via the refresh token on the agent's volume, so OAuth accounts need nothing here. Fill for a password account if the volume path ever fails." },
    { "key": "ANNA_AGENT_PASSWORD", "group": "anna", "type": "secret", "default": "", "advanced": true,
      "prompt": "Agent local password (fallback)",
      "help": "Companion to the username above. Stays on this machine; .env is gitignored." },
    { "key": "ANNA_IMAGE_VIA_COPILOT", "group": "anna", "type": "bool", "default": "false", "advanced": true,
      "prompt": "Experiment: ask the copilot for images?",
      "help": "Off by default: the agent's local API has no image endpoint and the copilot was observed to hallucinate image URLs. The game plays text-only without it." },

    { "key": "TEXT_PROVIDER", "group": "providers", "type": "choice", "choices": ["local", "openai"], "default": "local",
      "prompt": "Text provider",
      "help": "local = the llama.cpp container (8 stops + thinking). openai = any /chat/completions-compatible cloud; set the base URL, key and model below." },
    { "key": "TEXT_BASE_URL", "group": "providers", "type": "string", "default": "",
      "prompt": "Text base URL", "help": "Empty = the in-stack llama.cpp server. For cloud: the provider's API base." },
    { "key": "TEXT_API_KEY", "group": "providers", "type": "secret", "default": "",
      "prompt": "Text API key", "help": "Sent as Authorization: Bearer when set." },
    { "key": "TEXT_MODEL", "group": "providers", "type": "string", "default": "",
      "prompt": "Text model", "help": "Empty = the local alias. For cloud: the provider's model name." },
    { "key": "AUDIO_PROVIDER", "group": "providers", "type": "choice", "choices": ["local", "openai", "elevenlabs", "fal"], "default": "local",
      "prompt": "Audio provider",
      "help": "local = Maya1 voice-api. Cloud dialects are implemented against published schemas and pinned by contract tests; live verification is yours." },
    { "key": "AUDIO_BASE_URL", "group": "providers", "type": "string", "default": "",
      "prompt": "Audio base URL", "help": "Empty = the in-stack voice-api." },
    { "key": "AUDIO_API_KEY", "group": "providers", "type": "secret", "default": "",
      "prompt": "Audio API key", "help": "Provider key for cloud audio." },
    { "key": "AUDIO_MODEL", "group": "providers", "type": "string", "default": "",
      "prompt": "Audio model", "help": "Provider-specific model name; empty = each dialect's default." },
    { "key": "AUDIO_VOICE_POOL", "group": "providers", "type": "string", "default": "",
      "prompt": "ElevenLabs voice pool",
      "help": "elevenlabs only: comma-separated voice ids that characters map onto deterministically." },
    { "key": "IMAGE_PROVIDER", "group": "providers", "type": "choice", "choices": ["comfy", "openai", "gemini", "fal"], "default": "comfy",
      "prompt": "Image provider",
      "help": "comfy = the local image-api adapter over ComfyUI. openai = gpt-image-2, gemini = nano banana, fal = queue API." },
    { "key": "IMAGE_BASE_URL", "group": "providers", "type": "string", "default": "",
      "prompt": "Image base URL", "help": "Empty = the in-stack image-api." },
    { "key": "IMAGE_API_KEY", "group": "providers", "type": "secret", "default": "",
      "prompt": "Image API key", "help": "Provider key for cloud images." },
    { "key": "IMAGE_MODEL", "group": "providers", "type": "string", "default": "",
      "prompt": "Image model", "help": "Provider-specific model name; empty = each dialect's default." },

    { "key": "LLM_TEXT_PORT", "group": "text-llm", "type": "port", "default": "8080", "advanced": true,
      "prompt": "Text model port", "help": "Host port for the llama.cpp text server." },
    { "key": "LLM_CTX", "group": "text-llm", "type": "int", "default": "131072", "advanced": true,
      "prompt": "Context size",
      "help": "Reserve the model's FULL native 128K context. Per-slot context = LLM_CTX / LLM_PARALLEL." },
    { "key": "LLM_PARALLEL", "group": "text-llm", "type": "int", "default": "1", "advanced": true,
      "prompt": "Parallel slots", "help": "One slot keeps the whole context for one game; the engine is sequential anyway." },

    { "key": "COMFY_PORT", "group": "image-service", "type": "port", "default": "8188", "advanced": true,
      "prompt": "ComfyUI port", "help": "Host port for ComfyUI itself (the image-api talks to it container-to-container)." },
    { "key": "IMAGE_API_PORT", "group": "image-service", "type": "port", "default": "9001", "advanced": true,
      "prompt": "Image API port", "help": "Host port for the REST adapter in front of ComfyUI." },
    { "key": "IMAGE_DEFAULT_WIDTH", "group": "image-service", "type": "int", "default": "768", "advanced": true,
      "prompt": "Default image width", "help": "Scene fallback; the orchestrator normally passes sizes explicitly." },
    { "key": "IMAGE_DEFAULT_HEIGHT", "group": "image-service", "type": "int", "default": "768", "advanced": true,
      "prompt": "Default image height", "help": "Scene fallback height." },
    { "key": "IMAGE_DEFAULT_STEPS", "group": "image-service", "type": "int", "default": "4", "advanced": true,
      "prompt": "Diffusion steps", "help": "Tuned for the FLUX.2 Klein distilled model; more steps = slower, not necessarily better." },
    { "key": "IMAGE_CHAR_FACE_WIDTH", "group": "image-service", "type": "int", "default": "448", "advanced": true,
      "prompt": "Character face width", "help": "Face view is a square avatar." },
    { "key": "IMAGE_CHAR_FACE_HEIGHT", "group": "image-service", "type": "int", "default": "448", "advanced": true,
      "prompt": "Character face height", "help": "Keep equal to the width." },
    { "key": "IMAGE_CHAR_BODY_WIDTH", "group": "image-service", "type": "int", "default": "512", "advanced": true,
      "prompt": "Character body width", "help": "Body views are tall 9:16 so feet are not cropped (verified: wider frames crop)." },
    { "key": "IMAGE_CHAR_BODY_HEIGHT", "group": "image-service", "type": "int", "default": "912", "advanced": true,
      "prompt": "Character body height", "help": "Companion to the body width; keep the 9:16 ratio." },
    { "key": "IMAGE_GENERATE_TIMEOUT", "group": "image-service", "type": "int", "default": "120", "advanced": true,
      "prompt": "Per-image timeout (s)", "help": "Hard ceiling on one render before the adapter gives up." },
    { "key": "IMAGE_MAX_REFERENCES", "group": "image-service", "type": "int", "default": "4", "advanced": true,
      "prompt": "Max reference images", "help": "Identity references honored per render; klein tops out around 4." },

    { "key": "IMAGE_SCENE_W", "group": "image-knobs", "type": "int", "default": "640", "advanced": true,
      "prompt": "Scene art width", "help": "Orchestrator-side scene render size." },
    { "key": "IMAGE_SCENE_H", "group": "image-knobs", "type": "int", "default": "640", "advanced": true,
      "prompt": "Scene art height", "help": "Scene renders are roughly square." },
    { "key": "IMAGE_VIEW_W", "group": "image-knobs", "type": "int", "default": "960", "advanced": true,
      "prompt": "Look snapshot width", "help": "The wider 'what you see' shots." },
    { "key": "IMAGE_VIEW_H", "group": "image-knobs", "type": "int", "default": "640", "advanced": true,
      "prompt": "Look snapshot height", "help": "Companion height for look shots." },
    { "key": "IMAGE_AGENTIC_PROMPTS", "group": "image-knobs", "type": "bool", "default": "true", "advanced": true,
      "prompt": "LLM-written image prompts?",
      "help": "The text model writes each image prompt from live context (one extra LLM call per image). Off = template prompts." },
    { "key": "IMAGE_ITEMS", "group": "image-knobs", "type": "bool", "default": "true", "advanced": true,
      "prompt": "Item unlock cards?", "help": "Small card renders for newly visible items." },
    { "key": "IMAGE_ITEM_SIZE", "group": "image-knobs", "type": "int", "default": "320", "advanced": true,
      "prompt": "Item card size", "help": "Square item card edge in pixels." },
    { "key": "IMAGE_MAX_ITEMS_PER_TURN", "group": "image-knobs", "type": "int", "default": "2", "advanced": true,
      "prompt": "Item cards per turn", "help": "Cap so a generous narrator cannot flood the render queue." },
    { "key": "IMAGE_NARRATOR_COOLDOWN_TURNS", "group": "image-knobs", "type": "int", "default": "4", "advanced": true,
      "prompt": "Narrator image cooldown",
      "help": "Narrator-initiated images (show_image without a player look) at most every N turns." },

    { "key": "INTERPRET_FREE_TEXT", "group": "text-knobs", "type": "bool", "default": "true", "advanced": true,
      "prompt": "Interpret free text?",
      "help": "Plain typed text is interpreted into say/do/attack/give/whisper before resolving. Off = everything is a 'do'." },
    { "key": "CHARACTER_MAX_TOKENS", "group": "text-knobs", "type": "int", "default": "0", "advanced": true,
      "prompt": "Character reply cap (tokens)", "help": "0 = uncapped; the prompt discipline does the bounding." },
    { "key": "NARRATOR_THINKING", "group": "text-knobs", "type": "bool", "default": "true", "advanced": true,
      "prompt": "Narrator thinking?",
      "help": "A/B knob for hybrid-thinking models: request-level enable_thinking on the NARRATOR call only. Ignored by providers that do not support it." },
    { "key": "HISTORY_BEATS", "group": "text-knobs", "type": "int", "default": "80", "advanced": true,
      "prompt": "Story window (beats)",
      "help": "The verbatim story window fed to the narrator; older history rides the rolling facts-only recap. Also a per-game live setting." },
    { "key": "SUMMARY_ENABLED", "group": "text-knobs", "type": "bool", "default": "true", "advanced": true,
      "prompt": "Rolling recap?", "help": "Folds everything older than the window into a facts-only summary." },
    { "key": "SUMMARY_EVERY_TURNS", "group": "text-knobs", "type": "int", "default": "10", "advanced": true,
      "prompt": "Recap every N turns", "help": "How often the fold runs." },
    { "key": "SUMMARY_KEEP_TURNS", "group": "text-knobs", "type": "int", "default": "8", "advanced": true,
      "prompt": "Recap keeps newest N", "help": "The newest turns stay verbatim, never folded." },
    { "key": "MAX_CHARACTER_REACTIONS", "group": "text-knobs", "type": "int", "default": "2", "advanced": true,
      "prompt": "Voices per turn", "help": "At most this many characters speak per narrator reply. Raise for busier scenes." },
    { "key": "TURN_MAX_ACTOR_STEPS", "group": "text-knobs", "type": "int", "default": "4", "advanced": true,
      "prompt": "Cascade budget", "help": "Total actor steps in one turn before the engine closes the beat." },
    { "key": "TURN_MAX_PER_CHARACTER", "group": "text-knobs", "type": "int", "default": "1", "advanced": true,
      "prompt": "Speaks per character", "help": "Each character speaks at most this many times per turn." },
    { "key": "CHAR_HISTORY_BEATS", "group": "text-knobs", "type": "int", "default": "30", "advanced": true,
      "prompt": "Character memory window", "help": "Each character's verbatim window of beats THEY witnessed." },
    { "key": "CHAR_SUMMARY_ENABLED", "group": "text-knobs", "type": "bool", "default": "true", "advanced": true,
      "prompt": "Character recap?", "help": "Private rolling recap per character, folded in the background." },
    { "key": "CHAR_SUMMARY_EVERY", "group": "text-knobs", "type": "int", "default": "12", "advanced": true,
      "prompt": "Character recap every N", "help": "Witnessed beats that pile up before a fold." },
    { "key": "CHAR_SUMMARY_KEEP_TURNS", "group": "text-knobs", "type": "int", "default": "8", "advanced": true,
      "prompt": "Character recap keeps N", "help": "Newest witnessed turns stay verbatim." },
    { "key": "CHAR_SUMMARY_MAX_TOKENS", "group": "text-knobs", "type": "int", "default": "320", "advanced": true,
      "prompt": "Character recap cap", "help": "Token budget for one character recap." },

    { "key": "VOICE_API_PORT", "group": "voice", "type": "port", "default": "9002", "advanced": true,
      "prompt": "Voice API port", "help": "Host port for the Maya1 voice service (inside the network it listens on 8080)." },
    { "key": "LLM_VOICE_PORT", "group": "voice", "type": "port", "default": "9091", "advanced": true,
      "prompt": "Voice model port", "help": "Host port for the Maya1 SNAC-token server." },
    { "key": "LLM_VOICE_MODEL", "group": "voice", "type": "path-relative", "default": "maya1/maya1-q4_k_m.gguf", "advanced": true,
      "prompt": "Voice model file", "help": "Maya1 GGUF path relative to the models folder." },
    { "key": "LLM_VOICE_CTX", "group": "voice", "type": "int", "default": "4096", "advanced": true,
      "prompt": "Voice context size", "help": "SNAC token generation needs little context." }
  ],
  "constants": [
    { "key": "COMPOSE_PROFILES", "value": "local-inference-anna-false,anna-agent-anna-true",
      "comment": "DO NOT EDIT: makes the ANNA boolean drive the compose profiles. Local inference services carry local-inference-anna-${ANNA} (match only when ANNA=false); the Anna services carry anna-agent-anna-${ANNA} (match only when ANNA=true). One boolean, two service sets, no overlap." }
  ]
};
