/* Gamentic guided-tour step data.
   Loaded as a classic script (so index.html opens from file:// with no build,
   no modules, no CORS). Exposes one global: TUTORIAL_STEPS.

   Each step:
     region   - the group label shown in the caption eyebrow.
     sel      - CSS selector of the element to spotlight (a [data-tut] hook in
                index.html). Omit for an intro/outro card (full dim, no cutout).
     title    - short caption heading.
     body     - one or two sentences: what the element is.
     example  - a concrete example line (rendered in the accent color).
     stage    - optional overlay to open first: "profile" | "give" |
                "settings" | "lightbox". Omit to stay on the play screen.
     show     - optional array of data-reveal keys to un-hide for this step
                (e.g. the mid-turn "generating" row).
     place    - preferred caption placement: "below" | "above" | "auto".
     pad      - extra pixels of breathing room around the spotlight cutout. */

window.TUTORIAL_STEPS = [
  // ---- intro ------------------------------------------------------------
  {
    region: "Welcome",
    title: "This is where you play",
    body: "Gamentic is a self-hosted AI dungeon: you type what you want to do in plain words and an AI narrator writes the story back. This quick tour points out every part of the play screen.",
    example: "Use Next / Back, the arrow keys, or just click anywhere to move through it.",
  },

  // ---- the deck (header) -----------------------------------------------
  {
    region: "The deck",
    sel: '[data-tut="library"]',
    title: "Back to your library",
    body: "Leaves this adventure and returns to your shelf of saved worlds. Your progress is kept on your own machine, so you can walk away mid-scene.",
    example: "Tap it to jump out to \"Adventures\" and pick a different story.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="scene-name"]',
    title: "Where you are",
    body: "The name of your current location. Tap it to open an inspect sheet that describes the place in full and shows its art large.",
    example: "\"Rustwater Market\" - tap to read exactly what this bazaar is.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="mood"]',
    title: "Scene mood",
    body: "How charged the moment feels. It shifts with the story between calm, tense, and dangerous, and it colors how the narrator plays the scene.",
    example: "\"tense\" - amber, because an enforcer is watching you.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="clock"]',
    title: "The story clock",
    body: "Time of day inside the fiction, not your real clock. Night scenes, dawn raids, and deadlines all track from here.",
    example: "\"23:47 - Nightcycle\" - the market at its quietest and its most watched.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="scene-desc"]',
    title: "Scene description",
    body: "A one-line reminder of what this place looks, sounds, and smells like, so you always have the sensory frame in view.",
    example: "\"Rain sheets off the tarpaulins... somewhere a drone is hunting for you.\"",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="scene-items"]',
    title: "Scene items",
    body: "Things here you can interact with. A green + tag means loot you can take; a landmark tag means fixed scenery you can examine but not pocket. Tap any to inspect it.",
    example: "\"Cred-stick\" is takeable loot; the \"Sealed crate\" is bolted scenery.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="scene-actions"]',
    title: "Contextual actions",
    body: "Suggested things to try right here, offered by the narrator. They are shortcuts, never the only options - you can always just type your own move instead.",
    example: "\"Haggle with the vendor\" or \"Pry the crate open.\"",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="exits"]',
    title: "Ways out",
    body: "The exits revealed so far. One marked back returns the way you came. If nothing has been revealed yet, it reads \"Dead end\" until you find a route.",
    example: "\"Duck into the alley\" leads somewhere new; \"Back to the skybridge\" retreats.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="vitals"]',
    title: "Your vitals",
    body: "The heart bar is your life - if it empties, the story turns against you. The star is your points, a running score for clever and brave play.",
    example: "7/10 life after that stand-off, 320 points banked.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="context"]',
    title: "The memory meter",
    body: "How much of the tale the narrator can still hold in mind at once, in tokens. Green is comfortable, amber is filling, red means it is compressing older chapters into a recap.",
    example: "42.1k / 128k - plenty of headroom before anything folds into summary.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="goal"]',
    title: "Your current goal",
    body: "The objective the story is steering you toward right now. Tap it to open the full quest log and its checklist of steps.",
    example: "\"Find the fixer called Vessa\" - and she may be closer than you think.",
    place: "below",
  },
  {
    region: "The deck",
    sel: '[data-tut="menu"]',
    title: "Menu & settings",
    body: "Opens sound options and, during play, the rules of this adventure: difficulty, the narrator's voice, memory, and exporting the game.",
    example: "We open this later in the tour to look at difficulty and voice.",
    place: "below",
  },

  // ---- the story feed --------------------------------------------------
  {
    region: "The story",
    sel: '[data-tut="story"]',
    title: "The story feed",
    body: "The heart of the game: the narrator's tale unfolds here, newest at the bottom. Plain prose is narration you just read; the rest of this tour walks through each kind of beat.",
    example: "You can tap almost any moment here to ask the game what it meant.",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="scene-art"]',
    title: "Scene art",
    body: "The current scene painted as a collectible card, mixed right into the prose. It develops like a photograph as the image renders. Click it to open the scene sheet or expand the picture.",
    example: "The rain-lit skyline of Rustwater Market, anchored to this visit.",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="narration"]',
    title: "Narration",
    body: "The narrator's own voice, set like a book with no bubble or name. This is the connective tissue of the story - description, consequence, atmosphere.",
    example: "\"The market never really closes. It only lowers its voice.\"",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="speak"]',
    title: "Read it aloud",
    body: "Every spoken beat carries a voice button. Tap it to hear that line performed. Narration and character lines each get their own, and you can auto-play them from Settings.",
    example: "Tap to hear the narrator read this passage in the world's voice.",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="dialogue"]',
    title: "Character dialogue",
    body: "When someone speaks to you it lands in a named bubble in their own color, with their portrait. This is how you tell voices apart at a glance.",
    example: "Vessa Kade: \"You shouldn't have come down here in the rain, love.\"",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="char-action"]',
    title: "Character actions",
    body: "A character's deed, not their words, shown as a centered italic line in their color. It tells you what someone did without dressing it as speech.",
    example: "Rourke shifts his weight, one hand drifting toward his coat.",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="player-speech"]',
    title: "Your words, echoed",
    body: "When you say something it mirrors back as your own bubble, right-aligned in your color, so the conversation reads as a real exchange.",
    example: "You, to Vessa: \"I'm looking for a fixer. Word is you know her.\"",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="player-action"]',
    title: "Your actions, echoed",
    body: "Deeds you take come back as a quiet inline marker rather than a bubble, so your moves are visible in the log without shouting over the prose.",
    example: "you slide the cred-stick across the counter.",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="system"]',
    title: "System receipts",
    body: "Small animated badges mark things that just happened - items gained, points scored, traits unlocked, damage taken. Their color and icon tell you the kind at a glance.",
    example: "A green gem badge: \"Obtained: Cred-stick.\"",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="explain"]',
    title: "Tap to explain",
    body: "Not sure why something happened? Tap any receipt, beat, or item and the game explains what it meant and why - a built-in \"what just happened?\" for the whole log.",
    example: "Tap \"+40 points\" to learn it rewarded a clean, non-violent approach.",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="scene-shot"]',
    title: "Scene shots",
    body: "Dramatic moments and the results of looking closely arrive as full-width image beats, captioned with what you are seeing. Click to expand them.",
    example: "\"The alley behind the noodle stall, slick with rain.\"",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="item-card"]',
    title: "Item unlock cards",
    body: "When you gain a notable item it drops as a small square card with its own art and name - a collectible you keep. Click it to see it full size.",
    example: "A newly picked-up \"Neon-etched key-chip.\"",
    place: "auto",
  },
  {
    region: "The story",
    sel: '[data-tut="generating"]',
    title: "The narrator at work",
    body: "While a turn generates, this line shows who is thinking - the narrator, or a specific character replying - with pulsing dots, and the prose streams in as it is written.",
    example: "\"Vessa is replying...\" as her answer types itself out.",
    place: "above",
    show: ["generating"],
  },
  {
    region: "The story",
    sel: '[data-tut="stop"]',
    title: "Stop a turn",
    body: "Change your mind mid-turn? Stop cancels it as if it was never sent - your typed words come back to the composer so you can rewrite them.",
    example: "Hit Stop and \"I'm looking for a fixer...\" returns for you to edit.",
    place: "above",
    show: ["generating"],
  },
  {
    region: "The story",
    sel: '[data-tut="view-pending"]',
    title: "Rendering the view",
    body: "A Look turn always earns a picture, but it paints in the background and can land seconds later. This hint marks the wait until the image beat swaps in.",
    example: "\"rendering the view...\" after you study the alley.",
    place: "above",
    show: ["view-pending"],
  },

  // ---- the character column --------------------------------------------
  {
    region: "In the scene",
    sel: '[data-tut="party"]',
    title: "Who's here with you",
    body: "The characters standing in this scene, shown full figure. Everything you can do with a person lives one tap away in their profile.",
    example: "Right now: Vessa the fixer, and Rourke the enforcer.",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="char-card"]',
    title: "A character card",
    body: "Each person is a tall card with their reference art. Tap the art to open their full profile - traits, memories, and the private channel.",
    example: "Tap Vessa to open everything you know about her.",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="disposition"]',
    title: "How they feel about you",
    body: "Two badges ride each card: a relation (how you two stand) and a disposition (their current mood toward you), colored friendly, neutral, or hostile.",
    example: "Vessa reads \"ally\" and \"friendly\"; Rourke reads \"wary\" and \"hostile.\"",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="char-name"]',
    title: "Name & following",
    body: "Their name sits on a plate at the card's foot. A small compass tag means they are following you and will move between scenes at your side.",
    example: "\"Vessa Kade\" with a compass - she is coming with you.",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="char-hp"]',
    title: "Their health",
    body: "A slim bar under the name tracks a character's life the same way yours does, so you can read at a glance who is hurt.",
    example: "Vessa at 9/10 - a scratch, nothing more.",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="unread"]',
    title: "Unread whispers",
    body: "A count badge means this character has whispered you privately and you haven't read it. Open their profile's Whisper tab to catch up.",
    example: "Vessa has 2 unread whispers waiting for you.",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="char-memory"]',
    title: "Their own memory",
    body: "Each character is a separate AI with its own memory of what it has seen. This mini meter shows how full that character's recollection is.",
    example: "Vessa's memory: 18k / 64k - she remembers your whole night together.",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="char-carry"]',
    title: "What they carry",
    body: "A three-slot glimpse of a character's inventory. Empty slots hint at room for more; the full picture lives in their profile.",
    example: "Vessa is holding a \"Data-slate.\"",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="expand"]',
    title: "Expand to interact",
    body: "The card is a summary - to actually do something with a person (give, ask, whisper) you open their profile. This hint is the reminder.",
    example: "\"expand to interact\" - the doorway into everything about them.",
    place: "left",
  },
  {
    region: "In the scene",
    sel: '[data-tut="elsewhere"]',
    title: "Everyone elsewhere",
    body: "People you know who aren't standing here - followers lagging behind, those who left, and the fallen. You can still open their profile, and absent friends can still whisper you.",
    example: "Mireille is \"at the Spindle\"; Koto is \"fallen.\"",
    place: "left",
  },

  // ---- the action bar --------------------------------------------------
  {
    region: "The action bar",
    sel: '[data-tut="pack"]',
    title: "Your pack",
    body: "Everything you are carrying, with empty slots showing how much more you can hold. Tap an item to inspect it, or hand it over from a character's Give button.",
    example: "Cred-stick, Ramen chit, Old photo - three of six slots used.",
    place: "above",
  },
  {
    region: "The action bar",
    sel: '[data-tut="modes"]',
    title: "Say / Do / Look",
    body: "The line kind. Say speaks, Do acts, and Look studies the scene or one thing closely - Look can reveal what's hidden and often earns a picture. You can also just type and let the game figure out which you meant.",
    example: "Switch to Look, type \"the sealed crate,\" and study it.",
    place: "above",
  },
  {
    region: "The action bar",
    sel: '[data-tut="composer"]',
    title: "Type anything",
    body: "The main way to play: write what you do or say in your own words and press Enter. The game reads plain language into speech, deeds, attacks, gifts, even whispers.",
    example: "\"give the Old photo to Vessa\" just works, no menu needed.",
    place: "above",
  },
  {
    region: "The action bar",
    sel: '[data-tut="tag-btn"]',
    title: "Tag with @",
    body: "For precise control, tag a specific character or item so the game never guesses who you meant. Tagged entities become chips inside your line.",
    example: "The chips \"Old photo\" and \"Vessa\" pinned into the sentence above.",
    place: "above",
  },
  {
    region: "The action bar",
    sel: '[data-tut="stack"]',
    title: "Stack several lines",
    body: "The + button queues the current line and lets you compose another, so a whole sequence of moves resolves in one turn.",
    example: "Stack \"Whisper to Vessa: keep your voice down,\" then add your next move.",
    place: "above",
  },
  {
    region: "The action bar",
    sel: '[data-tut="send"]',
    title: "Send the turn",
    body: "Fires your line (or your whole stack) to the narrator. Enter does the same. While it resolves, the story feed shows the narrator working.",
    example: "Send, and Vessa answers.",
    place: "above",
  },
  {
    region: "The action bar",
    sel: '[data-tut="wish"]',
    title: "Whisper a wish",
    body: "An optional hope whispered to the storyteller, not an action you take. Easy difficulties lean into your wishes; hard ones may ignore them.",
    example: "\"let it stop raining, just for a minute.\"",
    place: "above",
  },
  {
    region: "The action bar",
    sel: '[data-tut="continue"]',
    title: "Continue on its own",
    body: "No input needed - Continue lets the story advance by itself, so the world keeps moving even when you just want to watch what happens next.",
    example: "Press Continue and Rourke makes the next move.",
    place: "above",
  },

  // ---- the profile screen ----------------------------------------------
  {
    region: "Character profile",
    stage: "profile",
    sel: '[data-tut="profile-art"]',
    title: "The full profile",
    body: "Opening a character fills the screen with them: their art large, with arrows to cycle through the portrait views the game has painted (full body, profile, face).",
    example: "Vessa Kade, in full - use the arrows to see her other angles.",
    place: "right",
  },
  {
    region: "Character profile",
    stage: "profile",
    sel: '[data-tut="profile-tabs"]',
    title: "Four tabs",
    body: "A character has four faces: Profile (who they are now), Traits (their personality), Memories (what you've shared), and Whisper (the private channel).",
    example: "The Whisper tab wears the same unread badge as the card: 2 waiting.",
    place: "below",
  },
  {
    region: "Character profile",
    stage: "profile",
    sel: '[data-tut="profile-status"]',
    title: "Profile tab",
    body: "The status sheet: gender, relation and mood, health, a description, what they carry, and the things you can DO to them right now - including Give.",
    example: "Actions offered: \"Give...\", \"Ask about the job,\" \"Offer to split the take.\"",
    place: "left",
  },
  {
    region: "Character profile",
    stage: "profile",
    sel: '[data-tut="profile-traits"]',
    title: "Traits tab",
    body: "A collection of personality cards the story unlocks as you interact. The more you play with a character, the more of who they are is revealed here.",
    example: "\"Never works for free.\" \"Softer than she lets anyone see.\"",
    place: "left",
  },
  {
    region: "Character profile",
    stage: "profile",
    sel: '[data-tut="profile-memories"]',
    title: "Memories tab",
    body: "The moments you've lived together: a strip of remembered images and a timeline of pivotal events, each stamped with the story clock.",
    example: "\"The night she pulled you off the skybridge.\"",
    place: "left",
  },
  {
    region: "Character profile",
    stage: "profile",
    sel: '[data-tut="profile-whisper"]',
    title: "Whisper tab",
    body: "A private, one-to-one channel only this character hears. Whisper, act discreetly, or look quietly - nothing here ever appears in the public story.",
    example: "You: \"Is Rourke a problem?\" Vessa: \"Keep him talking and follow my lead.\"",
    place: "left",
  },

  // ---- the give modal --------------------------------------------------
  {
    region: "Giving an item",
    stage: "give",
    sel: '[data-tut="give"]',
    title: "Hand something over",
    body: "The Give action opens your pack so you can choose exactly what to hand a character. Gifts can shift how someone feels about you.",
    example: "Give Vessa the \"Old photo\" and see what it stirs.",
    place: "auto",
  },

  // ---- settings --------------------------------------------------------
  {
    region: "Settings",
    stage: "settings",
    sel: '[data-tut="settings-audio"]',
    title: "Sound & voice",
    body: "Turn voice on or off, choose whether narration and character lines auto-speak as they arrive, and set the master volume. This is the global mute for the whole game.",
    example: "Voice on, character voices auto-speaking, volume at 70%.",
    place: "right",
  },
  {
    region: "Settings",
    stage: "settings",
    sel: '[data-tut="settings-difficulty"]',
    title: "Difficulty & narrator",
    body: "How much the world bends toward you - Easy grants your attempts and wishes, Hard refuses and punishes - plus the narrator's voice for spoken lines.",
    example: "Normal: the narrator weighs your attempts and wishes on their merits.",
    place: "left",
  },
  {
    region: "Settings",
    stage: "settings",
    sel: '[data-tut="settings-memory"]',
    title: "Story memory",
    body: "Tune how the narrator remembers: how much recent story stays word-for-word, and the token budget that caps how large its reading gets (and thus how fast turns run).",
    example: "Context budget 120k keeps turns snappy without losing the plot.",
    place: "right",
  },

  // ---- the lightbox ----------------------------------------------------
  {
    region: "Images up close",
    stage: "lightbox",
    sel: '[data-tut="lightbox"]',
    title: "The lightbox",
    body: "Clicking any picture - scene art, a scene shot, an item card, a memory - expands it here full size with its caption, so you can take in the detail.",
    example: "The rain-slicked alley, blown up with its caption beneath.",
    place: "auto",
  },

  // ---- outro -----------------------------------------------------------
  {
    region: "That's the tour",
    title: "You're ready to play",
    body: "That's every part of the play screen. The one thing to remember: you can always just type what you want in plain words - everything else is here to help, not to box you in.",
    example: "Replay the tour any time from the button in the corner.",
  },
];
